swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "评估中心"
basePath: "/eva/v1"
tags:

- name: "评估量表"
  description: "评估量表"
- name: "评估记录"
  description: "评估记录"
- name: "被评估人"
  description: "被评估人"
- name: "健康标尺"
  description: "健康标尺 & 健康标尺记录"


schemes:
- "http"
paths:
  /evaluation-bundles:
    get:
      tags:
        - "评估量表"
      description: "获取评估量表列表"
      operationId: "getEvaluationBundleList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: "departmentId"
          in: "query"
          description: "机构Id"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "成功\n返回结构见 EvaluationBundleListDTO"
          schema:
            $ref: "#/definitions/EvaluationBundleListDTO"
  
  /evaluation-submit-record/{evaluationSubmitRecordId}:
    get:
      tags:
        - "评估记录"
      description: "获取评估结果详情"
      operationId: "getEvaluationBundleRecordDetail"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: "evaluationSubmitRecordId"
          in: "path"
          description: "评估记录Id"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "成功\n返回结构见 EvaluationSubmitRecordDTO"
          schema:
            $ref: "#/definitions/EvaluationSubmitRecordDTO"
            
    post:
      tags:
        - "评估记录"
      description: "保存评估记录"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "updateEvaluationBundleRecordDetail"
      parameters:
        - name: "evaluationSubmitRecordId"
          in: "path"
          description: "评估记录Id"
          required: true
          type: "integer"
          format: "int64"
        - name: "body"
          in: "body"
          description: "\n请求结构见 EvaluationSubmitRecordOption"
          required: true
          schema:
            $ref: "#/definitions/EvaluationSubmitRecordOption"
      responses:
        200:
          description: "成功\n返回结构见 EvaluationSubmitRecordDTO"
          schema:
            $ref: "#/definitions/EvaluationSubmitRecordDTO"

  /evaluation-submit-record:
    get:
      tags:
        - "评估记录"
      description: "获取评估结果列表"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "addEvaluationBundleRecord"
      parameters:
        - name: "departmentId"
          in: "query"
          description: "机构Id"
          required: true
          type: "integer"
          format: "int64"
        - name: "evaluateeId"
          in: "query"
          description: "被评估人ID"
          required: false
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "成功\n返回结构见 EvaluationSubmitRecordListDTO"
          schema:
            $ref: "#/definitions/EvaluationSubmitRecordListDTO"
    post:
      tags:
        - "评估记录"
      description: "初始化评估记录"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "getEvaluationBundleRecordList"
      parameters:
        - name: "body"
          in: "body"
          description: "\n请求结构见 EvaluationSubmitRecordOption"
          required: true
          schema:
            $ref: "#/definitions/EvaluationSubmitRecordOption"
      responses:
        200:
          description: "成功\n返回结构见 EvaluationSubmitRecordDTO"
          schema:
            $ref: "#/definitions/EvaluationSubmitRecordDTO"

  /evaluatee:
    get:
      tags:
        - "被评估人"
      description: "获取被评估人列表"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "getEvaluateeList"
      responses:
        200:
          description: "成功\n返回结构见 EvaluateeListDTO"
          schema:
            $ref: "#/definitions/EvaluateeListDTO"
    
    post:
      tags:
        - "被评估人"
      description: "新建被评估人"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "addEvaluatee"
      parameters:
        - in: "body"
          name: "body"
          description: "\n请求结构见 EvaluateeOption"
          required: true
          schema:
            $ref: "#/definitions/EvaluateeOption"
      responses:
        200:
          description: "成功\n返回结构见 EvaluateeDTO"
          schema:
            $ref: "#/definitions/EvaluateeDTO"

  /evaluatee/{evaluateeId}:
    get:
      tags:
        - "被评估人"
      description: "获取被评估人详情"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "getEvaluateeDetail"
      parameters:
      - name: "evaluateeId"
        in: "path"
        description: "被评估人Id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "成功\n返回结构见 EvaluateeDTO"
          schema:
            $ref: "#/definitions/EvaluateeDTO"  
    patch:
      tags:
        - "被评估人"
      description: "编辑被评估人"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "updateEvaluateeDetail"
      parameters:
      - name: "evaluateeId"
        in: "path"
        description: "被评估人Id"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "\n请求结构见 EvaluateeOption"
        required: true
        schema:
          $ref: "#/definitions/EvaluateeOption"
      responses:
        200:
          description: "成功\n返回结构见 EvaluateeDTO"
          schema:
            $ref: "#/definitions/EvaluateeDTO"

  /evaluatee/{evaluateeId}/scales:
    get:
      tags:
        - "被评估人"
      description: "被评估人标尺信息"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "updateEvaluateeScales"
      parameters:
      - name: "evaluateeId"
        in: "path"
        description: "被评估人Id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "成功\n返回结构见ScaleValueDTO"
          schema:
            $ref: "#/definitions/ScaleValueDTO" 
definitions:
  Result:
    type: "object"
    properties:
      success:
        type: "boolean"
      code:
        type: "integer"
      msg:
        type: "string"
      displaymsg:
        type: "string"

  ScaleValueDTO:
    type: "object"
    properties:
      result:
        $ref: "#/definitions/Result"
      data:
        type: "object"
        properties:
          scale:
            type: "array"
            items:
              $ref: "#/definitions/ScaleValue"

  EvaluationBundleListDTO:
    type: "object"
    properties:
      result:
        $ref: "#/definitions/Result"
      data:
        type: "object"
        properties:
          evaluationBundleList:
            type: "array"
            items:
              $ref: "#/definitions/EvaluationBundleListItem"

  EvaluationBundleListItem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      desc:
        type: "string"
      version:
        type: "string"
      state:
        type: "string"
      stateName:
        type: "string"
      createdAt:
        type: "integer"
        format: "int64"
      updatedAt:
        type: "integer"
        format: "int64"
        
  EvaluationModule:
    type: "object"
    properties:
      name:
        type: "string"
      code:
        type: "string"
      version:
        type: "string"        
      sections:
        type: "array"
        items:
          $ref: "#/definitions/EvaluationSection"

  EvaluationSubmitRecordDTO:
    type: "object"
    properties:
      result:
        $ref: "#/definitions/Result"
      data:
        type: "object"
        properties:
          recordDetail: 
            $ref: "#/definitions/EvaluationSubmitRecordDetail"
  
  EvaluationSubmitRecordDetail:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "评估记录ID"
      evaluationConclusion:
        type: "string"
        description: "结论"
      evaluationModule:
        $ref: "#/definitions/EvaluationModule"
  
  EvaluationSubmitRecordListDTO:
    type: "object"
    properties:
      result:
        $ref: "#/definitions/Result"
      data:
        type: "object"
        properties:
          evaluationSubmitRecordList: 
            type: "array"
            items:
              $ref: "#/definitions/EvaluationSubmitRecord"
  
  EvaluationSubmitRecord:
    type: "object"
    properties:
      evaluationSubmitRecordId:
        type: "integer"
        format: "int64"
        description: "评估记录ID"
      evaluateeId:
        type: "integer"
        format: "int64"
        description: "被评估人ID"
      evaluateeName:
        type: "string"
        description: "被评估人姓名"
      evaluationBundleId:
        type: "integer"
        format: "int64"
        description: "评估量表ID"
      evaluationBundleName:
        type: "string"
        description: "评估名称"
      departmentId:
        type: "integer"
        format: "int64"
        description: "机构ID"
      departmentName:
        type: "string"
        description: "机构名称"
      state:
        type: "string"
        description: "状态"
      stateName:
        type: "string"
        description: "状态" 
      updatedAt:
        type: "integer"
        format: "int64"

  EvaluationSubmitRecordOption:
    type: "object"
    properties:
      evaluationBundleId:
        type: "integer"
        format: "int64"
        description: "评估量表ID"
      departmentId:
        type: "integer"
        format: "int64"
        description: "机构ID"
      evaluateeId:
        type: "integer"
        format: "int64"
        description: "被评估人ID"
      taskId:
        type: "integer"
        format: "int64"
        description: "评估任务ID"     

  EvaluateeListDTO:
    type: "object"
    properties:
      result:
        $ref: "#/definitions/Result"
      data:
        type: "object"
        properties:
          evaluateeList: 
            type: "array"
            items:
              $ref: "#/definitions/EvaluateeDetail"

  EvaluateeDetail:
    type: "object"
    description: "被评估人员"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "被评估人ID"
      name:
        type: "string"
        description: "被评估人姓名"
      birthday:
        type: "integer"
        format: "int64"
        description: "被评估人生日"
      age:
        type: "integer"
        format: "int64"
        description: "被评估人年龄"
      gender:
        type: "integer"
        format: "int64"
        description: "被评估人性别"
      phone:
        type: "string"
        description: "手机号"
      idCard:
        type: "string"
        description: "身份证号码"
      socialCard:
        type: "string"
        description: "社保卡号"
      address:
        type: "string"
        description: "地址"
      createdAt:
        type: "integer"
        format: "int64"
      updatedAt:
        type: "integer"
        format: "int64"

  EvaluateeDTO:
    type: "object"
    properties:
      result:
        $ref: "#/definitions/Result"
      data:
        type: "object"
        properties:
          evaluatee: 
            $ref: "#/definitions/EvaluateeDetail"
  
  EvaluateeOption:
    type: "object"
    description: "被评估人员"
    properties:
      name:
        type: "string"
        description: "被评估人姓名"
      birthday:
        type: "integer"
        format: "int64"
        description: "被评估人生日"
      gender:
        type: "integer"
        format: "int64"
        description: "被评估人性别"
      phone:
        type: "string"
        description: "手机号"
      idCard:
        type: "string"
        description: "身份证号码"
      socialCard:
        type: "string"
        description: "社保卡号"
      address:
        type: "string"
        description: "地址"

  Question:
    type: "object"
    properties:
      id: 
        type: "string"
        description: "题目唯一标识"
      order:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        description: "标题"
      description:
        type: "string"
        description: "描述"
      type:
        type: "string"
        description: "题目类型,有4种:completion(填空),single_choice(单选),multi_choice(多选),bundle(量表题)"
      repeat:
        type: "boolean"
        description: "题目是否需要重复"
      properties:
        type: "array"
        items:
          $ref: "#/definitions/CompletionProperty"
      options:
        type: "array"
        items:
          $ref: "#/definitions/ChoiceOption"
      content:
        $ref: "#/definitions/EvaluationSection"
       
  ChoiceOption:
    type: "object"
    properties:
      order:
        type: "integer"
      content:
        type: "string"
        description: "选项内容"
      weight:
        type: "integer"
    
  CompletionProperty:
    type: "object"
    properties:
      require:
        type: "boolean"
        description: "是否必填"
      text_before:
        type: "string"
        description: "填空前面的说明"
      blank_type:
        type: "string"
        description: "空的类型,有2种:SELECTION(带选项),TEXT(空白),NUM(只填数值的空白)"
      chosen_value:
        type: "array"
        description: "选项"
        items:
          type: "string"
      blank_placeholder:
        type: "string"
      text_after:
        type: "string"
        description: "填空后面的说明"
      newline:
        type: "boolean"
        description: "是否需要换行"
      # wikiNodeId:
      #   type: "integer"
      #   format: "int64"
      #   description: "关联的自然人节点ID"
 
  EvaluationSection:
    type: "object"
    properties:
      name:
        type: "string"
        description: "名称"
      type:
        type: "string"
        description: "类型"
      is_grouped:
        type: "boolean"
        description: "是否分组"
      group:
        type: "array"
        description: "有分组时"
        items:
          $ref: "#/definitions/QuestionGroup"
      questions:
        type: "array"
        description: "题目列表（无分组时）"
        items:
          $ref: "#/definitions/Question"

  QuestionGroup:
    type: "object"
    properties:
      name:
        type: "string"
        description: "名称"
      code:
        type: "string"
        description: "标识"
      questions:
        type: "array"
        description: "题目列表"
        items:
          $ref: "#/definitions/Question"

  ScaleValue:
    type: "object"
    properties:
      latest:
        description: "最近一次标尺数据"
        $ref: "#/definitions/ScaleValueHistoryItem"
      history:
        description: "标尺历史数据"
        type: "array"
        items:
          $ref: "#/definitions/ScaleValueHistoryItem"
      scale_mark:
        description: "标尺刻度"
        type: "array"
        items:
          $ref: "#/definitions/ScaleMark"
      scale_max_value:
        type: "integer"
        description: "标尺刻度最大值"
        
  
  ScaleValueHistoryItem:
    type: "object"
    properties:
      value:
        type: "integer"
        description: "标尺值"
      description:
        type: "string"
        description: "标尺值描述"
      date:
        type: "integer"
        description: "标尺值时间"
      default_color:
        type: "string"
        description: "默认颜色"

  ScaleMark:
    type: "object"
    properties:
      mark:
        type: "string"
        description: "标尺刻度值区间"
      description:
        type: "string"
        description: "标尺值描述"
      default_color:
        type: "string"
        description: "默认颜色"