swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "蜂邻项目C端"
basePath: "/weixin/v1"
tags:

- name: "评估量表"
  description: "评估量表"
- name: "被评估人"
  description: "被评估人"
# - name: "我的"
#   description: "客户详情接口"


schemes:
- "http"
paths:
  /evaluation-bundles:
    get:
      tags:
        - "评估量表"
      description: "获取评估量表"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "成功\n返回结构见 EvaluationBundleListDTO"
          schema:
            $ref: "#/definitions/EvaluationBundleListDTO"

  /evaluatee:
    get:
      tags:
        - "被评估人"
      description: "获取被评估人列表"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "成功\n返回结构见 EvaluateeListDTO"
          schema:
            $ref: "#/definitions/EvaluateeListDTO"

definitions:
  EvaluationBundleListDTO:
    type: "object"
    properties:
      result:
        schema:
          $ref: "#/definitions/Result"
      evaluationBundle:
        type: "array"
        schema:
          $ref: "#/definitions/EvaluationBundleListItem"

  EvaluationBundleListItem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      desc:
        type: "string"
      version:
        type: "string"
      createdAt:
        type: "integer"
        format: "int64"
      updatedAt:
        type: "integer"
        format: "int64"

  EvaluationBundleDetail:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      desc:
        type: "string"
      type:
        type: "integer"
        format: "int64"
      typeName:
        type: "string"
      departmentId":
        type: "integer"
        format: "int64"
      state":
        type: "integer"
        format: "int64"
      stateName:
        type: "string"
      identity:
        type: "string"
        description: "量表标志编码"
      version:
        type: "string"
      createdAt:
        type: "integer"
        format: "int64"
      updatedAt:
        type: "integer"
        format: "int64"
  #     content:
  #       schema:
  #         $ref: "#/definitions/EvaluationBundleContent"
  #
  # EvaluationBundleContent:
  #   type: "object"
  #   properties:



  EvaluationBundleDTO:
    type: "object"
    properties:
      result:
        schema:
          $ref: "#/definitions/Result"
      evaluationBundle:
        type: "array"
        schema:
          $ref: "#/definitions/EvaluationBundleDetail"
  Result:
    type: "object"
    properties:
      success:
        type: "boolean"
      code:
        type: "integer"
      msg:
        type: "string"
      displamsg:
        type: "string"

  EvaluateeListDTO:
    type: "object"
    properties:
      result:
        schema:
          $ref: "#/definitions/Result"
      data:
        type: "object"
        properties:
          evaluateeList: 
            type: "array"
            schema:
              $ref: "#/definitions/EvaluateeDetail"

  EvaluateeDetail:
    type: "object"
    description: "被评估人员"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "被评估人ID"
      name:
        type: "string"
        description: "被评估人姓名"
      birthday:
        type: "integer"
        format: "int64"
        description: "被评估人生日"
      age:
        type: "integer"
        format: "int64"
        description: "被评估人年龄"
      gender:
        type: "integer"
        format: "int64"
        description: "被评估人性别"
      phone:
        type: "string"
        description: "手机号"
      idCard:
        type: "string"
        description: "身份证号码"
      socialCard:
        type: "string"
        description: "社保卡号"
      address:
        type: "string"
        description: "地址"
 