stages:
  - push
  - rebuild

before_script:
  - echo `pwd` # debug
  - echo `java -version`
  - echo "$JAVA_HOME"
  - echo `which java`

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/libs/*.jar

push:
  stage: push
  script:
    - sudo docker login -u 7@youhujia.com -p Youhujia2016 registry-vpc.cn-beijing.aliyuncs.com
    - sudo docker build -t registry-vpc.cn-beijing.aliyuncs.com/zhushou-dev/api-doc:latest .
    - sudo docker push registry-vpc.cn-beijing.aliyuncs.com/zhushou-dev/api-doc:latest

rebuild:
  stage: push
  script:
  - curl 'https://cs.console.aliyun.com/hook/trigger?triggerUrl=YzU3MjU1NTE1NDM2NDRiNTk5ZWUxMDg4ZjdmMTM5NmE4fGFwaS1kb2N8cmVkZXBsb3l8MWE2dnIwc2JkNGttanw=&secret=6a564332537a367270704d686b726a710ec8b23e01e49acff9227451679a101b'

after_script:
  - echo "End CI"
